apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: service-track-ordens
spec:
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
