apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: service-track-ordens

resources:
  - ../../base

components:
  - ../../componentes/kafka-efemero
  - ../../componentes/nodeport

images:
  - name: servicetrack-ordens
    newName: 734564927706.dkr.ecr.us-east-1.amazonaws.com/servicetrack-prd-ordens
    newTag: placeholder

patches:
  - path: hpa-patch.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: service-track-ordens-config
    literals:
      - ST_ORD_DB_POOL_MAX=10
      - ST_ORD_DB_POOL_MIN=2
      - ST_ORD_MESSAGING_ENABLED=true
      - KAFKA_BOOTSTRAP_SERVERS=service-track-ordens-kafka.service-track-ordens.svc.cluster.local:9092
      - KAFKA_ADMIN_FAIL_FAST=true
      - OTEL_JAVAAGENT_ENABLED=false
